/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "DMA_1_dma.h"
#include "ISR_Sw.h"
#include "PIN_ADC_IN_1_aliases.h"
#include "PIN_ADC_IN_1.h"
#include "ISR_DMA_1.h"
#include "PIN_SWITCH_aliases.h"
#include "PIN_SWITCH.h"
#include "ISR_DMA_2.h"
#include "PIN_ADC_IN_AZ_aliases.h"
#include "PIN_ADC_IN_AZ.h"
#include "DMA_2_dma.h"
#include "ADC_SAR_2.h"
#include "Clock_aclk.h"
#include "Clock_soc.h"
#include "UART_1.h"
#include "ADC_SAR_1.h"
#include "PWM.h"
#include "Clock_PWM.h"
#include "H_ENA_aliases.h"
#include "H_ENA.h"
#include "H_ENB_aliases.h"
#include "H_ENB.h"
#include "H_INA_aliases.h"
#include "H_INA.h"
#include "H_INB_aliases.h"
#include "H_INB.h"
#include "PWMout_aliases.h"
#include "PWMout.h"
#include "S_EN_aliases.h"
#include "S_EN.h"
#include "S_STEP_aliases.h"
#include "S_STEP.h"
#include "S_DIR_aliases.h"
#include "S_DIR.h"
#include "PWM_step.h"
#include "Clock_PWM_step.h"
#include "PIN_ADC_IN_EL_aliases.h"
#include "PIN_ADC_IN_EL.h"
#include "AMux_1.h"
#include "ADC_SAR_2_IRQ.h"
#include "ADC_SAR_2_Bypass_aliases.h"
#include "ADC_SAR_2_Bypass.h"
#include "UART_1_IntClock.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_Bypass_aliases.h"
#include "ADC_SAR_1_Bypass.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

